# Development overrides for BLS+frontend Compose

services:

  frontend:
    # Bind mount properties file for quick updates during development
    volumes:
      - ./docker/config/corpus-frontend.properties:/etc/blacklab/corpus-frontend.properties

  frontend-proxy:
    # Bind mount properties file for quick updates during development
    volumes:
      - ./docker/config/corpus-frontend.properties:/etc/blacklab/corpus-frontend.properties
